name: Jobs
on: 
  push:
  
jobs:
  this-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - name: Testspace push test content
        run: |
          - testspace "[${{ github.workflow }}/${{ github.job}}]./testcontent/*.xml"
          - exit 1
        if: always()
  that-job:
    runs-on: ubuntu-latest
    needs: [this-job]
    steps:
      - uses: actions/checkout@v2
      - run: echo "THAT_JOB"
  fan-in-job:
    runs-on: ubuntu-latest
    needs: [that-job]
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"