name: Jobs
on: 
  - push 
  - workflow_dispatch
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: http://mark.testspace.test:3000
          #token: ${{secrets.TS_TOKEN}}
      - run: exit 1
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job}}]./testcontent/*.xml"
        if: always()
  setup:
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:
      - uses: actions/checkout@v4
      - run: echo "THAT_JOB"
  fan-in-job:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        jobId: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/checkout@v4
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: http://mark.testspace.test:3000
          #token: ${{secrets.TS_TOKEN}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ matrix.jobId }}]./testcontent/*.xml"